name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    container:
      image: birudeghi/continuousgpt:beta
      ports:
        - 8080
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth login -e && flyctl auth token
        env:
          FLYCTL_AUTH_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl secrets set OPENAI_KEY=${{ secrets.OPENAI_KEY }}
      - run: flyctl deploy --remote-only
        env:
          FLYCTL_AUTH_TOKEN: ${{ secrets.FLY_API_TOKEN }}